<?php

namespace Proxies\__CG__\Quartet\Bundle\KakarotBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Day extends \Quartet\Bundle\KakarotBundle\Entity\Day implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function addLikeSchedule(\Quartet\Bundle\KakarotBundle\Entity\LikeSchedule $likeSchedules)
    {
        $this->__load();
        return parent::addLikeSchedule($likeSchedules);
    }

    public function removeLikeSchedule(\Quartet\Bundle\KakarotBundle\Entity\LikeSchedule $likeSchedules)
    {
        $this->__load();
        return parent::removeLikeSchedule($likeSchedules);
    }

    public function getLikeSchedules()
    {
        $this->__load();
        return parent::getLikeSchedules();
    }

    public function addDaySetting(\Quartet\Bundle\KakarotBundle\Entity\DaySetting $daySettings)
    {
        $this->__load();
        return parent::addDaySetting($daySettings);
    }

    public function removeDaySetting(\Quartet\Bundle\KakarotBundle\Entity\DaySetting $daySettings)
    {
        $this->__load();
        return parent::removeDaySetting($daySettings);
    }

    public function getDaySettings()
    {
        $this->__load();
        return parent::getDaySettings();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'likeSchedules', 'daySettings');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}